{{- range $name, $value := .Values.agentGroups }}
---
{{ if $value.clearmlConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-conf
data:
  clearml.conf: {{ $value.clearmlConfig | b64enc }}
{{ end }}
{{- end }}
